version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing AWS CDK CLI..."
      - npm install -g aws-cdk
      - echo "Changing into backend directory"
      - cd backend
      - echo "Installing npm dependencies"
      - npm ci

  pre_build:
    commands:
      - |
        if [ "$ACTION" != "destroy" ]; then
          echo "Building TypeScript sources";
          npm run build;
          echo "Bootstrapping CDK (no approval)...";
          cdk bootstrap --require-approval never \
            -c knowledgeBaseId=$KNOWLEDGE_BASE_ID \
            -c githubOwner=$GITHUB_OWNER \
            -c githubRepo=$GITHUB_REPO \
            -c documentsBucketName=$DOCUMENTS_BUCKET || true;
        else
          echo "Destroy mode - skipping build and bootstrap";
        fi

  build:
    commands:
      - >-
        if [ "$ACTION" = "destroy" ]; then
          echo "Destroying CDK stack...";
          echo "Cleaning up k8s security groups...";
          
          # Delete k8s security groups by name pattern
          aws ec2 describe-security-groups --filters "Name=group-name,Values=k8s-*" --query 'SecurityGroups[].GroupId' --output text 2>/dev/null | xargs -r -n1 aws ec2 delete-security-group --group-id 2>/dev/null || true;
          
          # Wait for cleanup
          sleep 10;
          
          cdk destroy --force;
        else
          echo "Deploying CDK stack...";
          cdk deploy --require-approval never \
            -c knowledgeBaseId=$KNOWLEDGE_BASE_ID \
            -c githubOwner=$GITHUB_OWNER \
            -c githubRepo=$GITHUB_REPO \
            -c documentsBucketName=$DOCUMENTS_BUCKET;
        fi

  post_build:
    commands:
      - |
        if [ "$ACTION" != "destroy" ]; then
          echo "Triggering Amplify build...";
          sleep 30;
          
          # Try multiple times to get the App ID
          for i in {1..5}; do
            AMPLIFY_APP_ID=$(aws cloudformation describe-stacks \
              --stack-name AgentEksFargateStack \
              --query 'Stacks[0].Outputs[?OutputKey==`ExportAmplifyAppId`].OutputValue' \
              --output text 2>/dev/null);
            
            if [ -n "$AMPLIFY_APP_ID" ] && [ "$AMPLIFY_APP_ID" != "None" ]; then
              echo "Found Amplify App ID: $AMPLIFY_APP_ID";
              aws amplify start-job \
                --app-id $AMPLIFY_APP_ID \
                --branch-name full-cdk \
                --job-type RELEASE && echo "Amplify build started successfully" || echo "Amplify build trigger failed";
              break;
            else
              echo "Attempt $i: App ID not found, waiting...";
              sleep 10;
            fi;
          done;
        fi
      - 'echo "CDK $ACTION complete."'