version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing AWS CDK CLI..."
      - npm install -g aws-cdk
      - echo "Changing into backend directory"
      - cd backend
      - echo "Installing npm dependencies"
      - npm ci

  pre_build:
    commands:
      - |
        if [ "$ACTION" != "destroy" ]; then
          echo "Building TypeScript sources";
          npm run build;
          echo "Bootstrapping CDK (no approval)...";
          cdk bootstrap --require-approval never \
            -c knowledgeBaseId=$KNOWLEDGE_BASE_ID \
            -c githubOwner=$GITHUB_OWNER \
            -c githubRepo=$GITHUB_REPO \
            -c documentsBucketName=$DOCUMENTS_BUCKET || true;
        else
          echo "Destroy mode - skipping build and bootstrap";
        fi

  build:
    commands:
      - >-
        if [ "$ACTION" = "destroy" ]; then
          echo "Destroying CDK stack...";
          
          # First attempt CDK destroy
          cdk destroy --force || {
            echo "CDK destroy failed, cleaning up k8s security groups...";
            
            # Delete k8s security groups
            aws ec2 describe-security-groups --filters "Name=group-name,Values=k8s-*" --query 'SecurityGroups[].GroupId' --output text 2>/dev/null | xargs -r -n1 aws ec2 delete-security-group --group-id 2>/dev/null || true;
            
            # Wait for cleanup
            sleep 10;
            
            # Retry CDK destroy
            echo "Retrying CDK destroy...";
            cdk destroy --force;
          };
        else
          echo "Deploying CDK stack...";
          cdk deploy --require-approval never \
            -c knowledgeBaseId=$KNOWLEDGE_BASE_ID \
            -c githubOwner=$GITHUB_OWNER \
            -c githubRepo=$GITHUB_REPO \
            -c documentsBucketName=$DOCUMENTS_BUCKET;
        fi

  post_build:
    commands:
      - |
        if [ "$ACTION" = "destroy" ]; then
          echo "";
          echo "ðŸ—‘ï¸  DESTROY COMPLETE! ðŸ—‘ï¸";
          echo "All resources have been successfully destroyed.";
          echo "";
        else
          echo "";
          echo "ðŸš€ DEPLOYMENT COMPLETE! ðŸš€";
          echo "Your iECHO RAG Chatbot is now live!";
          echo "";
          echo "ðŸ“‹ Deployment Summary:";
          
          # Get URLs from CDK stack outputs
          API_URL=$(aws cloudformation describe-stacks --stack-name AgentFargateStack --query 'Stacks[0].Outputs[?OutputKey==`ExportApiGatewayUrl`].OutputValue' --output text 2>/dev/null);
          AMPLIFY_URL=$(aws cloudformation describe-stacks --stack-name AgentFargateStack --query 'Stacks[0].Outputs[?OutputKey==`ExportAmplifyAppUrl`].OutputValue' --output text 2>/dev/null);
          AMPLIFY_APP_ID=$(aws cloudformation describe-stacks --stack-name AgentFargateStack --query 'Stacks[0].Outputs[?OutputKey==`ExportAmplifyAppId`].OutputValue' --output text 2>/dev/null);
          
          echo "   ðŸŒ API Gateway: $API_URL";
          echo "   ðŸ“± Frontend: https://$AMPLIFY_URL";
          
          # Trigger Amplify build (optional)
          if [ -n "$AMPLIFY_APP_ID" ] && [ "$AMPLIFY_APP_ID" != "None" ]; then
            echo "";
            echo "Triggering Amplify build...";
            aws amplify start-job --app-id $AMPLIFY_APP_ID --branch-name main --job-type RELEASE >/dev/null 2>&1 && echo "âœ… Amplify build started" || echo "ðŸ”„ Amplify build already running or failed";
          fi;
          
          echo "";
          echo "âœ… Ready to use!";
        fi