version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing AWS CDK CLI..."
      - npm install -g aws-cdk
      - |
        if [ "$ACTION" != "destroy" ]; then
          echo "Changing into backend directory";
          cd backend;
          echo "Installing npm dependencies";
          npm ci;
        else
          echo "Destroy mode - skipping npm install";
        fi

  pre_build:
    commands:
      - |
        if [ "$ACTION" != "destroy" ]; then
          echo "Building TypeScript sources";
          npm run build;
          echo "Bootstrapping CDK (no approval)...";
          cdk bootstrap --require-approval never \
            -c knowledgeBaseId=$KNOWLEDGE_BASE_ID \
            -c githubOwner=$GITHUB_OWNER \
            -c githubRepo=$GITHUB_REPO \
            -c documentsBucketName=$DOCUMENTS_BUCKET || true;
        else
          echo "Destroy mode - skipping build and bootstrap";
          cd backend;
        fi

  build:
    commands:
      - >-
        if [ "$ACTION" = "destroy" ]; then
          echo "Destroying CDK stack...";
          echo "Cleaning up security groups...";
          aws ec2 describe-security-groups --filters "Name=group-name,Values=k8s-*" --query 'SecurityGroups[].GroupId' --output text 2>/dev/null | xargs -r -n1 aws ec2 delete-security-group --group-id 2>/dev/null || true;
          cdk destroy --force;
        else
          echo "Deploying CDK stack...";
          cdk deploy --require-approval never \
            -c knowledgeBaseId=$KNOWLEDGE_BASE_ID \
            -c githubOwner=$GITHUB_OWNER \
            -c githubRepo=$GITHUB_REPO \
            -c documentsBucketName=$DOCUMENTS_BUCKET;
        fi

  post_build:
    commands:
      - |
        if [ "$ACTION" != "destroy" ]; then
          echo "Triggering Amplify build...";
          AMPLIFY_APP_ID=$(aws cloudformation describe-stacks \
            --stack-name AgentEksFargateStack \
            --query 'Stacks[0].Outputs[?OutputKey==`ExportAmplifyAppId`].OutputValue' \
            --output text);
          if [ -n "$AMPLIFY_APP_ID" ]; then
            aws amplify start-job \
              --app-id $AMPLIFY_APP_ID \
              --branch-name full-cdk \
              --job-type RELEASE || echo "Amplify build trigger failed";
          fi;
        fi
      - 'echo "CDK $ACTION complete."'